Update patch set 2
Patch Set 2: Verified-1

Hmm, this plugin doesn't work for me, but I don't see what is wrong.

[2016-11-15 09:31:22,183] [main] WARN  com.google.gerrit.server.plugins.PluginLoader : Cannot load plugin example-simpleSshCommand
com.google.gerrit.server.plugins.InvalidPluginException: Unable to load plugin Guice Modules
  at com.google.gerrit.server.plugins.ServerPlugin.loadGuiceModules(ServerPlugin.java:90)
  ...
Caused by: java.lang.ClassNotFoundException: com.googlesource.gerrit.plugins.examples.simplesshcommand.SshModule
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381) 
  ...

Patch-set: 2
Label: Verified=-1