Update patch set 1
Patch Set 1:

Hi David, was wondering if you might be able to help me get this plugin building in Bazel. Having the extra directory level between ‘plugins’ and the actual plugin (example-simpleSshCommand) is causing issues. I get the following output:

ERROR: /Users/jmelvin/Documents/Qualcomm/Working/gerrit/upstream_gerrit/plugins/examples/example-simpleSshCommand/BUILD:3:1: Executing genrule //plugins/examples/example-simpleSshCommand:example-simpleSshCommand failed: bash failed: error executing command
  (cd /private/var/tmp/_bazel_jmelvin/167d9f936f1fd455689cb5496d863686/execroot/upstream_gerrit && \
  exec env - \
    PATH=/opt/local/bin:/opt/local/sbin:/users/jmelvin/Documents/Qualcomm/Working/buck/bin:/users/jmelvin/Documents/Qualcomm/Working/buck/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/sbin:/usr/local/sbin \
    TMPDIR=/var/folders/qr/sx877f0141d9pzmwbbndg22r002_mz/T/ \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; ROOT=$PWD && TMP=$(mktemp -d || mktemp -d -t bazel-tmp) && (GEN_VERSION=$(cat bazel-out/stable-status.txt | grep EXAMPLE-SIMPLESSHCOMMAND | cut -d '\'' '\'' -f 2) && cd $TMP && unzip -q $ROOT/bazel-out/local-fastbuild/bin/plugins/examples/example-simpleSshCommand/example-simpleSshCommand__non_stamped_deploy.jar && echo "Implementation-Version: $GEN_VERSION
$(cat META-INF/MANIFEST.MF)" > META-INF/MANIFEST.MF && zip -qr $ROOT/bazel-out/local-fastbuild/genfiles/plugins/examples/example-simpleSshCommand/example-simpleSshCommand.jar .)'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
Target //plugins/examples/example-simpleSshCommand:example-simpleSshCommand failed to build
INFO: Elapsed time: 0.778s, Critical Path: 0.39s

If I put the ‘example-simpleSshCommand’ up one directory level, the build works. I’ve been poking around with Bazel, but still very new to the tool. Any help would be appreciated.

Also, I’ve noticed the issue with BSD mktemp vs. GNU mktemp, any suggestions on how to get around that? Thanks!

Patch-set: 1
Reviewer: Gerrit User 1033742 <1033742@173816e5-2b9a-37c3-8a2e-48639d4f1153>